blank_issues_enabled: false
contact_links:
    - name: BTDstudios Discord
      url: Coming Soon...
      about: Our support Discord, please ask questions and search for help here.
    - name: BTDstudios Website
      url: https://btdstudios.github.io/
      about: Please look here for frequently asked questions, updates and questions on how to use the client.