name: '💬 General Request'
description: Report incorrect translations.
title: '[General]: '
labels:
    - 'Type: General'
    - 'Status: /'

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this general request for the BTDclient! Fill out the following form to your best ability to help us answer your request.
              Only use this if your request doesn't fit into any other category.
              For anything else, use: our Discord server (Coming Soon) or [our website](https://btdstudios.github.io/).

    - type: textarea
      attributes:
          label: Provide a description of your request
          placeholder: Add a short description why you want to open this general request.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots / Videos
          description: If applicable, add screenshots to your request.

    - type: textarea
      attributes:
          label: Contact details
          description: You can provide information how to contact you for further information. Note that the contact information can be seen by everyone.

    - type: checkboxes
      attributes:
          label: Checklist
          description: Make sure you have followed each of the steps displayed here.
          options:
              - label: I have included the required information.
                required: true
              - label: I have searched through the list of opened issues if this request already exists.
                required: true

    - type: textarea
      attributes:
          label: Anything else?
          description: You can provide additional context below.